name: Bump Package Version
description: Automatically bump npm package version.
author: Alexey Yakovlev <alexeyyakovlev0359@gmail.com>
runs:
  using: node12
  main: index.js
inputs:
  minor-wording:
    description: "Words list that trigger a minor version bump"
    default: "feat,minor"
    required: false
  major-wording:
    description: "Words list that trigger a major version bump"
    default: "BREAKING CHANGE,major"
    required: false
  patch-wording:
    description: "Words list that trigger a patch version bump"
    required: false
  commit-message:
    description: "Set a custom commit message for version bump commit"
    required: false
  skip-push:
    description: "Skip pushes"
    required: false
    default: false
  skip-commit:
    description: "Skip commits"
    required: false
    default: false
  skip-tag:
    description: "Skip tagging"
    required: false
    default: false
  skip-for-canary:
    description: "Skip commiting, tagging and pushing for canary versions (PRs)"
    required: false
    default: true
  abort-for-forks:
    description: "Abort action when running in a PR from a fork"
    required: false
    default: true
